<?php
// GENERATED by bump_version
return [
    'master_branch' => 'master',
    'develop_branch' => 'develop',
    'version_file' => __DIR__ . '/VERSION',
    // 'define_version_file' => __DIR__ . '/app/version.php', // you can add a 'PHP accessible' define with the current version
    // 'define_version_name' => 'APP_VERSION', // the define name
    // 'changelog_file' => __DIR__ . '/CHANGELOG', // A basic CHANGELOG
    'release_branches' => ['hotfix' => 'hotfix-*', 'release' => 'release-*'], // The branches you should release on
];
